# Generated by Django 2.0.6 on 2018-06-06 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='english',
        ),
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='tibetan',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
