# Generated by Django 2.0.6 on 2018-06-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20180606_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='bhutia',
        ),
    ]
